# Generated by Django 2.2.6 on 2019-10-04 20:53

from django.db import migrations, models


STATUS_DEFAULTS = {
    "FAILED": {"weight": -30, "color": "#cc0000", "icon": "fa fa-times-circle-o"},
    "ERROR": {"weight": -20, "color": "#cc0000", "icon": "fa fa-minus-circle"},
    "BLOCKED": {"weight": -10, "color": "#cc0000", "icon": "fa fa-stop-circle-o"},
    "IDLE": {"weight": 0, "color": "#72767b", "icon": "fa fa-question-circle-o"},
    "PAUSED": {"weight": 0, "color": "#72767b", "icon": "fa fa-pause-circle-o"},
    "RUNNING": {"weight": 0, "color": "#72767b", "icon": "fa fa-play-circle-o"},
    "WAIVED": {"weight": 10, "color": "#92d400", "icon": "fa fa-commenting-o"},
    "PASSED": {"weight": 20, "color": "#92d400", "icon": "fa fa-check-circle-o"},
}


def insert_default_values(apps, schema_editor):
    test_execution_status_model = apps.get_model("testruns", "TestExecutionStatus")

    existing = {s.name: s for s in test_execution_status_model.objects.all()}
    for name, attrs in STATUS_DEFAULTS.items():
        if name in existing:
            status = existing[name]
            for key, val in attrs.items():
                setattr(status, key, val)
            status.save()
        else:
            test_execution_status_model.objects.create(name=name, **attrs)


class Migration(migrations.Migration):
    dependencies = [
        ("testruns", "0006_rename_test_case_run_to_test_execution"),
    ]

    operations = [
        migrations.AddField(
            model_name="testexecutionstatus",
            name="icon",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="testexecutionstatus",
            name="color",
            field=models.CharField(default="", max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="testexecutionstatus",
            name="weight",
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(insert_default_values, migrations.RunPython.noop),
    ]
